language: php
php:
  - "5.4"
  - "5.3"
branches:
  only:
    - master
env:
  global:
    - secure: "KRBDUp2mqR7y12nSUzxaExownlISzSR0O5F1AjckB+G2Yfvox0lbZMBaYKqp/YasuHM8LE7Fcm9HsnUDzZcSYI5GSfMMMCF4QdqbiQ0Y4UVpKAtNhU8BDZltmScommvjK11F9HaGck3+QodJNGoDj+lNDmhgFRHHtt5OY8QFDKU="
    - "REPOSITORY=visualcaptcha-php"
before_script:
  - composer install
after_success:
  - "curl --data 'deploy={\"repository\":\"$REPOSITORY\",\"branch\":\"$TRAVIS_BRANCH\"}' http://githooks.emotionloop.com/?k=$AUTH_KEY"
